userAgent: "Heliosbot/0.1 (+https://github.com/eseoa)"
server:
  port: "${PORT:8080}"
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    tomcat:
      max-active: 10
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      enable_lazy_load_no_trans: true
      dialect: "org.hibernate.dialect.MySQL5Dialect"
      ddl-auto: create
sites:
    - url: "https://lenta.ru/"
      name: "lenta"
    - url: "http://www.proview.ru"
      name: "proview.ru"
    - url: "http://site1.com"
      name: "site1"
    - url: "https://skillbox.ru/"
      name: "skillbox"




